f=open("abc.txt","r+")
print("file name:",f.name)
print("file mode:",f.mode)
print("is file readble:",f.readable())
print("is file writable:",f.writable())
print("is file closed:",f.closed)
f.close()
print("is file closed:",f.closed)
